---
system_packages:
  - build-essential
  - git
  - curl
  - make
  - vim
  - unzip
  - nodejs 
  - graphicsmagick
  - nginx
  - clang 
  - whois
  - python-setuptools
  - python-dateutil
  - python-software-properties 
  - python-gdal 
  - python-mapnik2 
  - python-pyproj
  - python-dev 
  - python-imaging
  - python-virtualenv
  - postgis
  - zlib1g-dev
  - subversion
  - doxygen
  - graphviz
  - pgadmin3
  - gdal-bin
  - libpq-dev
  - libgdal-dev


